# -*- coding: utf-8 -*-
"""奇偶替换.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zdVZd3lffggFlGy7cvU1MbZ4uwX28nlb
"""

import re

def replace_occurrences(text, word, replacements):
    count = 0
    new_text = ''
    last_end = 0  # Track the end index of the last found word

    for m in re.finditer(rf'\b{word}\b', text, re.IGNORECASE):
        count += 1
        start, end = m.start(), m.end()
        replacement = replacements[count % 2]  # Choose the replacement based on odd or even occurrence

        new_text += text[last_end:start] + replacement  # Add the text from the last end index to the start of the found word, and then the replacement
        last_end = end  # Update the last end index

    new_text += text[last_end:]  # Add any remaining text
    return new_text

# Step 1: Read the content of the file "file_to_read.txt"
with open('file_to_read.txt', 'r') as f:
    content = f.read()

# Step 2: Calculate the total number of occurrences of the word "terrible"
word_to_count = "terrible"
total_occurrences = content.lower().count(word_to_count)
print(f"The word 'terrible' appears {total_occurrences} times.")

# Step 3 and 4: Replace occurrences and write to a new file
replacements = ["marvellous", "pathetic"]
new_content = replace_occurrences(content, word_to_count, replacements)

# Write the new content to a new file
with open('result.txt', 'w') as f:
    f.write(new_content)

print("Replacements done. The new content has been written to 'result.txt'.")