# -*- coding: utf-8 -*-
"""电影检索3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Jz0rkJj58UWZ43J_9FJt3Sp0OnQkHhp
"""

import sqlite3

# Step 1: Read data from the file
filepath = 'stephen_king_adaptations.txt'
with open(filepath, 'r') as f:
    data_lines = [line.strip() for line in f]

# Step 2: Establish a connection with the SQLite database and create a new table
db_filepath = 'sk_movies_db.db'
connection = sqlite3.connect(db_filepath)
cursor = connection.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS SKMovies (
        MovieID TEXT,
        Title TEXT,
        YearOfRelease INT,
        IMDBScore REAL
    )
''')
connection.commit()

# Step 3: Insert data from the list into the table
for data_line in data_lines:
    MovieID, Title, YearOfRelease, IMDBScore = data_line.split(',')

    cursor.execute('''
        INSERT INTO SKMovies (MovieID, Title, YearOfRelease, IMDBScore)
        VALUES (?, ?, ?, ?)
    ''', (MovieID, Title, int(YearOfRelease), float(IMDBScore)))

connection.commit()

# Step 4: Create a user interface to search the database
def user_interface():
    while True:
        print("\nPlease select an option:")
        print("1. Search by title")
        print("2. Search by year of release")
        print("3. Search by IMDB score")
        print("4. Exit")

        user_option = input("Your selection: ")

        if user_option == "1":
            title_query = input("Enter the movie title: ")

            cursor.execute("SELECT * FROM SKMovies WHERE Title LIKE ?", ('%' + title_query + '%',))
            query_results = cursor.fetchall()

            if query_results:
                for result in query_results:
                    print(f"Movie ID: {result[0]}, Title: {result[1]}, Year of Release: {result[2]}, IMDB Score: {result[3]}")
            else:
                print("No movies found with that title.")

        elif user_option == "2":
            year_query = int(input("Enter the year of release: "))

            cursor.execute("SELECT * FROM SKMovies WHERE YearOfRelease = ?", (year_query,))
            query_results = cursor.fetchall()

            if query_results:
                for result in query_results:
                    print(f"Movie ID: {result[0]}, Title: {result[1]}, Year of Release: {result[2]}, IMDB Score: {result[3]}")
            else:
                print("No movies found from that year.")

        elif user_option == "3":
            score_query = float(input("Enter the minimum IMDB score: "))

            cursor.execute("SELECT * FROM SKMovies WHERE IMDBScore >= ?", (score_query,))
            query_results = cursor.fetchall()

            if query_results:
                for result in query_results:
                    print(f"Movie ID: {result[0]}, Title: {result[1]}, Year of Release: {result[2]}, IMDB Score: {result[3]}")
            else:
                print("No movies found with an IMDB score above the specified value.")

        elif user_option == "4":
            print("Exiting the program. Goodbye!")
            break
        else:
            print("Invalid option. Please try again.")

# Launch the user interface
user_interface()